/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Insets;

import javax.swing.JButton;

/**
 *
 * @author ADMIN
 */
public class GUI_ChonVe extends javax.swing.JFrame {

    /**
     * Creates new form GUI_ChonVe
     */
    public GUI_ChonVe() {
        initComponents();
        addButtonsToPanelE(); 
        addButtonsToPanelF();
        addButtonsToPanelG();
        addButtonsToPanelH();
        addButtonsToPanelK();
        addButtonsToPanelI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        panelE = new javax.swing.JPanel();
        panelF = new javax.swing.JPanel();
        panelG = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        panelH = new javax.swing.JPanel();
        panelK = new javax.swing.JPanel();
        panelI = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 540));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(21, 115, 135));
        jTextField1.setText("Chọn chỗ ngồi ");
        jTextField1.setPreferredSize(new java.awt.Dimension(145, 40));
        jPanel1.add(jTextField1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 210));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1131, 200));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 0, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jTextField3.setText("Ghế Thương Gia");
        jPanel6.add(jTextField3, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(153, 153, 0));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.GridLayout(0, 1));

        jTextField7.setText("A");
        jPanel14.add(jTextField7);

        jTextField8.setText("B");
        jPanel14.add(jTextField8);

        jPanel10.add(jPanel14, java.awt.BorderLayout.LINE_START);

        jPanel17.setLayout(new java.awt.GridLayout(0, 1));

        jButton5.setText("1");
        jPanel17.add(jButton5);

        jButton1.setText("2");
        jPanel17.add(jButton1);

        jButton6.setText("1");
        jPanel17.add(jButton6);

        jButton2.setText("2");
        jPanel17.add(jButton2);

        jPanel10.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(0, 255, 204));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jTextField5.setText("Ghế Phổ Thông");
        jPanel7.add(jTextField5, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(204, 255, 102));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel18.setLayout(new java.awt.GridLayout(0, 1));

        jTextField11.setText("E");
        jPanel18.add(jTextField11);

        jTextField12.setText("F");
        jPanel18.add(jTextField12);

        jTextField13.setText("G");
        jPanel18.add(jTextField13);

        jPanel12.add(jPanel18, java.awt.BorderLayout.LINE_START);

        jPanel19.setLayout(new java.awt.GridLayout(0, 1));

        panelE.setLayout(new java.awt.GridLayout(1, 0));
        jPanel19.add(panelE);

        panelF.setLayout(new java.awt.GridLayout(1, 0));
        jPanel19.add(panelF);

        panelG.setLayout(new java.awt.GridLayout(1, 0));
        jPanel19.add(panelG);

        jPanel12.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1131, 80));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jTextField2.setText("ĐƯỜNG ĐI ");
        jPanel4.add(jTextField2);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 255, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(1131, 210));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jTextField4.setText("Ghế Thương Gia");
        jPanel8.add(jTextField4, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBackground(new java.awt.Color(204, 204, 0));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 92));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.GridLayout(0, 1));

        jTextField9.setText("C");
        jPanel15.add(jTextField9);

        jTextField10.setText("D");
        jPanel15.add(jTextField10);

        jPanel11.add(jPanel15, java.awt.BorderLayout.LINE_START);

        jPanel16.setLayout(new java.awt.GridLayout(0, 1));

        jButton7.setText("1");
        jPanel16.add(jButton7);

        jButton3.setText("2");
        jPanel16.add(jButton3);

        jButton8.setText("1");
        jPanel16.add(jButton8);

        jButton4.setText("2");
        jPanel16.add(jButton4);

        jPanel11.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel9.setBackground(new java.awt.Color(0, 255, 204));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jTextField6.setText("Ghế Phổ Thông");
        jPanel9.add(jTextField6, java.awt.BorderLayout.PAGE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel23.setLayout(new java.awt.GridLayout(0, 1));

        jTextField14.setText("H");
        jPanel23.add(jTextField14);

        jTextField15.setText("K");
        jPanel23.add(jTextField15);

        jTextField16.setText("I");
        jPanel23.add(jTextField16);

        jPanel13.add(jPanel23, java.awt.BorderLayout.LINE_START);

        jPanel24.setLayout(new java.awt.GridLayout(0, 1));

        panelH.setLayout(new java.awt.GridLayout(1, 0));
        jPanel24.add(panelH);

        panelK.setLayout(new java.awt.GridLayout(1, 0));
        jPanel24.add(panelK);

        panelI.setLayout(new java.awt.GridLayout(1, 0));
        jPanel24.add(panelI);

        jPanel13.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonsToPanelE() {
        // Tạo và thêm 50 button vào jPanel20
        for (int i = 1; i <= 50; i++) {
            JButton button = new JButton("" + i); // Tạo button với tên
            button.setFont(new Font("Arial", Font.PLAIN, 8));
            button.setMargin(new Insets(0, 0, 0, 0));
            panelE.add(button); // Thêm button vào panel
        }


    }
    
    private void addButtonsToPanelF() {
        // Tạo và thêm 50 button vào jPanel20
        for (int i = 1; i <= 50; i++) {
            JButton button = new JButton("" + i); // Tạo button với tên
            button.setFont(new Font("Arial", Font.PLAIN, 8));
            button.setMargin(new Insets(0, 0, 0, 0));
            panelF.add(button); // Thêm button vào panel
        }


    }
    
    private void addButtonsToPanelG() {
        // Tạo và thêm 50 button vào jPanel20
        for (int i = 1; i <= 50; i++) {
            JButton button = new JButton("" + i); // Tạo button với tên
            button.setFont(new Font("Arial", Font.PLAIN, 8));
            button.setMargin(new Insets(0, 0, 0, 0));
            panelG.add(button); // Thêm button vào panel
        }


    }
    
    private void addButtonsToPanelH() {
        // Tạo và thêm 50 button vào jPanel20
        for (int i = 1; i <= 50; i++) {
            JButton button = new JButton("" + i); // Tạo button với tên
            button.setFont(new Font("Arial", Font.PLAIN, 8));
            button.setMargin(new Insets(0, 0, 0, 0));
            panelH.add(button); // Thêm button vào panel
        }


    }
    
    private void addButtonsToPanelK() {
        // Tạo và thêm 50 button vào jPanel20
        for (int i = 1; i <= 50; i++) {
            JButton button = new JButton("" + i); // Tạo button với tên
            button.setFont(new Font("Arial", Font.PLAIN, 8));
            button.setMargin(new Insets(0, 0, 0, 0));
            panelK.add(button); // Thêm button vào panel
        }


    }
    
    private void addButtonsToPanelI() {
        // Tạo và thêm 50 button vào jPanel20
        for (int i = 1; i <= 50; i++) {
            JButton button = new JButton("" + i); // Tạo button với tên
            button.setFont(new Font("Arial", Font.PLAIN, 8));
            button.setMargin(new Insets(0, 0, 0, 0));
            panelI.add(button); // Thêm button vào panel
        }


    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ChonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ChonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ChonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ChonVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ChonVe().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelE;
    private javax.swing.JPanel panelF;
    private javax.swing.JPanel panelG;
    private javax.swing.JPanel panelH;
    private javax.swing.JPanel panelI;
    private javax.swing.JPanel panelK;
    // End of variables declaration//GEN-END:variables
}
