/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.Date;

import javax.imageio.ImageReader;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

import java.awt.Component;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;

import DAO.DAO_LichBay;
import DAO.DAO_VeMayBay;
import ENTITY.LichBay;
import ENTITY.VeMayBay;

/**
 *
 * @author ADMIN
 */
public class GUI_DatVe extends javax.swing.JPanel {

	/**
	 * Creates new form GUI_DatVe
	 */
	private GUI_ChonVe gui_ChonVe;
	private String tieude[] = { "Mã Vé", "Hãng Bay", "Điểm Đi", "Điểm Đến", "Ngày Giờ Đi", "Ngày Giờ Đến", "Thời Gian",
			"Giá" };
	private DefaultTableModel modeltable = new DefaultTableModel(tieude, 0);
	

	// DAO
	private DAO_LichBay dao_LichBay = new DAO_LichBay();
	private DAO_VeMayBay dao_VeMayBay = new DAO_VeMayBay();

	// LIST
	private ArrayList<LichBay> listLichBay;
	private ArrayList<VeMayBay> listVeBay;

	public GUI_DatVe() {
		listLichBay = dao_LichBay.getalltbLichBay();
		listVeBay = dao_VeMayBay.getalltbVeMayBay();

		initComponents();
		
		duaDuLieuVaoModule();
		duaDuLieuVaoNoiDi(cbNoiDi);
		duaDuLieuVaoNoiDen(cbNoiDen);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrLoaiVe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rdbtnMotChieu = new javax.swing.JRadioButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        rdbtnKhuHoi = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jlbNoiDi = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        cbNoiDi = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jlbNoiDen = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        cbNoiDen = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jlbThoiGianDi = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        jdateNgayDi = new com.toedter.calendar.JDateChooser();
        jPanel14 = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jlbThoiGianVe = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        jdateNgayVe = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        btnSapXepTheoGia = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        btnDatVe = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        btnTimVe = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        btnDatLai = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 115, 135));
        jLabel1.setText("ĐẶT VÉ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(276, 100));

        rdbtnMotChieu.setBackground(new java.awt.Color(255, 255, 255));
        btnGrLoaiVe.add(rdbtnMotChieu);
        rdbtnMotChieu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        rdbtnMotChieu.setForeground(new java.awt.Color(21, 115, 135));
        rdbtnMotChieu.setSelected(true);
        rdbtnMotChieu.setText("Một Chiều");
        rdbtnMotChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnMotChieuActionPerformed(evt);
            }
        });
        jPanel3.add(rdbtnMotChieu);
        jPanel3.add(filler2);

        rdbtnKhuHoi.setBackground(new java.awt.Color(255, 255, 255));
        btnGrLoaiVe.add(rdbtnKhuHoi);
        rdbtnKhuHoi.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        rdbtnKhuHoi.setForeground(new java.awt.Color(21, 115, 135));
        rdbtnKhuHoi.setText("Khứa Hồi");
        rdbtnKhuHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnKhuHoiActionPerformed(evt);
            }
        });
        jPanel3.add(rdbtnKhuHoi);
        jPanel3.add(filler1);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(462, 650));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(modeltable);
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(80);
        jTable1.setSelectionBackground(new java.awt.Color(21, 115, 135));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel4.add(filler11, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(954, 150));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));
        jPanel9.add(filler12);

        jlbNoiDi.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlbNoiDi.setForeground(new java.awt.Color(21, 115, 135));
        jlbNoiDi.setText("Nơi Đi ");
        jlbNoiDi.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel9.add(jlbNoiDi);
        jPanel9.add(filler4);
        jPanel9.add(cbNoiDi);

        jPanel6.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));
        jPanel10.add(filler13);

        jlbNoiDen.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlbNoiDen.setForeground(new java.awt.Color(21, 115, 135));
        jlbNoiDen.setText("Nơi Đến");
        jlbNoiDen.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel10.add(jlbNoiDen);
        jPanel10.add(filler5);
        jPanel10.add(cbNoiDen);

        jPanel6.add(jPanel10);

        jPanel5.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));
        jPanel13.add(filler7);

        jlbThoiGianDi.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlbThoiGianDi.setForeground(new java.awt.Color(21, 115, 135));
        jlbThoiGianDi.setText("Thời Gian Đi");
        jlbThoiGianDi.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel13.add(jlbThoiGianDi);
        jPanel13.add(filler3);
        jPanel13.add(jdateNgayDi);

        jPanel7.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));
        jPanel14.add(filler8);

        jlbThoiGianVe.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jlbThoiGianVe.setForeground(new java.awt.Color(21, 115, 135));
        jlbThoiGianVe.setText("Thời Gian Về");
        jlbThoiGianVe.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel14.add(jlbThoiGianVe);
        jPanel14.add(filler6);

        jdateNgayVe.setEnabled(false);
        jPanel14.add(jdateNgayVe);

        jPanel7.add(jPanel14);

        jPanel5.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));
        jPanel11.add(filler9);

        btnSapXepTheoGia.setBackground(new java.awt.Color(21, 115, 135));
        btnSapXepTheoGia.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnSapXepTheoGia.setForeground(new java.awt.Color(255, 255, 255));
        btnSapXepTheoGia.setText("Lọc Theo Giá");
        btnSapXepTheoGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTheoGiaActionPerformed(evt);
            }
        });
        jPanel11.add(btnSapXepTheoGia);

        jPanel8.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));
        jPanel12.add(filler10);

        btnDatVe.setBackground(new java.awt.Color(21, 115, 135));
        btnDatVe.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnDatVe.setForeground(new java.awt.Color(255, 255, 255));
        btnDatVe.setText("Đặt Vé");
        btnDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatVeActionPerformed(evt);
            }
        });
        jPanel12.add(btnDatVe);

        jPanel8.add(jPanel12);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        filler14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.add(filler14);

        btnTimVe.setBackground(new java.awt.Color(21, 115, 135));
        btnTimVe.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnTimVe.setForeground(new java.awt.Color(255, 255, 255));
        btnTimVe.setText("Tìm Vé");
        btnTimVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimVeActionPerformed(evt);
            }
        });
        jPanel15.add(btnTimVe);

        jPanel8.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        filler15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.add(filler15);

        btnDatLai.setBackground(new java.awt.Color(21, 115, 135));
        btnDatLai.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnDatLai.setForeground(new java.awt.Color(255, 255, 255));
        btnDatLai.setText("Đặt Lại ");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });
        jPanel16.add(btnDatLai);

        jPanel8.add(jPanel16);

        jPanel5.add(jPanel8);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void rdbtnMotChieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdbtnMotChieuActionPerformed
		jdateNgayVe.setEnabled(false);
		jdateNgayVe.setDate(null);
	}// GEN-LAST:event_rdbtnMotChieuActionPerformed

	private void rdbtnKhuHoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdbtnKhuHoiActionPerformed
		jdateNgayVe.setEnabled(true);
	}// GEN-LAST:event_rdbtnKhuHoiActionPerformed

	private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDatLaiActionPerformed
		modeltable.setRowCount(0);
		for (VeMayBay veMayBay : listVeBay) {
			// Tính khoảng cách thời gian
			Duration khoangCach = Duration.between(veMayBay.getMaLichBay().getThoiGianDi(),
					veMayBay.getMaLichBay().getThoiGianDen());

			// Thêm dữ liệu vào bảng
			modeltable.addRow(new Object[] { veMayBay.getMaVe(), veMayBay.getMaHangBay().getTenHangBay(),
					veMayBay.getMaLichBay().getNoiDi(), veMayBay.getMaLichBay().getNoiDen(),
					veMayBay.getMaLichBay().getThoiGianDi(), veMayBay.getMaLichBay().getThoiGianDen(),
					khoangCach.toHoursPart() + "h" + khoangCach.toMinutesPart() + "m", veMayBay.getGia() });
		}
		jdateNgayVe.setDate(null);
		jdateNgayDi.setDate(null);
	}// GEN-LAST:event_btnDatLaiActionPerformed

	private void btnSapXepTheoGiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSapXepTheoGiaActionPerformed
		// Lọc danh sách vé đang hiển thị trên bảng, giả sử bạn có một danh sách mới với
		// các vé đang hiện trên table
		ArrayList<VeMayBay> filteredList = new ArrayList<>();

		// Lọc các vé có trong bảng (ví dụ như bạn có thể sử dụng modeltable để xác
		// định)
		for (int i = 0; i < modeltable.getRowCount(); i++) {
			String maVe = (String) modeltable.getValueAt(i, 0);
			VeMayBay veMayBay = dao_VeMayBay.getOneObjVeMayBay(maVe); // Lấy thông tin VeMayBay từ mã vé
			if (veMayBay != null) {
				filteredList.add(veMayBay);
			}
		}

		// Sắp xếp danh sách vé theo giá
		filteredList.sort((v1, v2) -> Double.compare(v1.getGia(), v2.getGia()));

		// Cập nhật lại model table
		modeltable.setRowCount(0); // Xóa tất cả các dòng hiện tại
		for (VeMayBay veMayBay : filteredList) {
			Duration khoangCach = Duration.between(veMayBay.getMaLichBay().getThoiGianDi(),
					veMayBay.getMaLichBay().getThoiGianDen());
			modeltable.addRow(new Object[] { veMayBay.getMaVe(), veMayBay.getMaHangBay().getTenHangBay(),
					veMayBay.getMaLichBay().getNoiDi(), veMayBay.getMaLichBay().getNoiDen(),
					veMayBay.getMaLichBay().getThoiGianDi(), veMayBay.getMaLichBay().getThoiGianDen(),
					khoangCach.toHoursPart() + "h" + khoangCach.toMinutesPart() + "m", veMayBay.getGia() });
		}
	}// GEN-LAST:event_btnSapXepTheoGiaActionPerformed

	private void btnDatVeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDatVeActionPerformed
	    int selectedRow = jTable1.getSelectedRow(); //kiểm tra có chọn dòng chưa
	    if (selectedRow == -1) { 
	        JOptionPane.showMessageDialog(this, "Vui lòng chọn vé trong bảng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
	        return; // Kết thúc sự kiện
	    }

	    // Kiểm tra người dùng đã chọn loại vé (một chiều hoặc khứ hồi) chưa
	    if (rdbtnKhuHoi.isSelected() || rdbtnMotChieu.isSelected()) {
	        gui_ChonVe = new GUI_ChonVe();
	        gui_ChonVe.setVisible(true);
	        gui_ChonVe.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	        gui_ChonVe.setLocationRelativeTo(null);
	    } else {
	        JOptionPane.showMessageDialog(this, "Bạn muốn đi một chiều hay khứ hồi? Hãy chọn 1 trong 2", "Thông báo",
	                JOptionPane.INFORMATION_MESSAGE);
	    }
	}// GEN-LAST:event_btnDatVeActionPerformed

	private void btnTimVeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimVeActionPerformed

		// Lấy giá trị từ combobox
		String noiDi = cbNoiDi.getSelectedItem().toString();
		String noiDen = cbNoiDen.getSelectedItem().toString();

		// Kiểm tra nếu nơi đi và nơi đến trùng nhau
		if (noiDi.equals(noiDen)) {
			JOptionPane.showMessageDialog(this, "Nơi đi và nơi đến không được trùng!", "Thông báo",
					JOptionPane.WARNING_MESSAGE);
			return; // Dừng xử lý tại đây
		}

		// Kiểm tra ngày đi và ngày về
		Date dateNgayDi = jdateNgayDi.getDate();
		Date dateNgayVe = jdateNgayVe.getDate();

		if (dateNgayDi != null && dateNgayVe != null) {
			LocalDate ngayDi = dateNgayDi.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
			LocalDate ngayVe = dateNgayVe.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

			if (!ngayVe.isAfter(ngayDi)) { // Ngày về phải sau ngày đi
				JOptionPane.showMessageDialog(this, "Ngày về phải sau ngày đi!", "Thông báo",
						JOptionPane.WARNING_MESSAGE);
				return; // Dừng xử lý tại đây
			}
		}

		// Xóa tất cả các dòng trong bảng
		modeltable.setRowCount(0);

		boolean coKetQua = false; // Cờ để kiểm tra có kết quả hay không

		// Lấy giá trị từ jdateNgayDi (nếu chưa lấy ở trên)
		LocalDate ngayDi = null;
		if (dateNgayDi != null) {
			ngayDi = dateNgayDi.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		}

		for (VeMayBay veMayBay : listVeBay) {
			// Lấy thời gian đi từ VeMayBay
			LocalDateTime thoiGianDi = veMayBay.getMaLichBay().getThoiGianDi();

			// Kiểm tra điều kiện
			if (veMayBay.getMaLichBay().getNoiDi().equals(noiDi) && veMayBay.getMaLichBay().getNoiDen().equals(noiDen)
					&& (ngayDi == null || thoiGianDi.toLocalDate().equals(ngayDi))) {

				// Tính khoảng cách thời gian
				Duration khoangCach = Duration.between(thoiGianDi, veMayBay.getMaLichBay().getThoiGianDen());

				// Thêm dữ liệu vào bảng
				modeltable.addRow(new Object[] { veMayBay.getMaVe(), veMayBay.getMaHangBay().getTenHangBay(),
						veMayBay.getMaLichBay().getNoiDi(), veMayBay.getMaLichBay().getNoiDen(), thoiGianDi,
						veMayBay.getMaLichBay().getThoiGianDen(),
						khoangCach.toHoursPart() + "h" + khoangCach.toMinutesPart() + "m", veMayBay.getGia() });

				coKetQua = true; // Có ít nhất một kết quả phù hợp
			}
		}

		// Nếu không có kết quả nào, hiển thị thông báo
		if (!coKetQua) {
			JOptionPane.showMessageDialog(this, "Không có chuyến bay phù hợp!", "Thông báo",
					JOptionPane.INFORMATION_MESSAGE);
		}

	} // GEN-LAST:event_btnTimVeActionPerformed

	// Dua du lieu vào comboBox và modole table
	public void duaDuLieuVaoNoiDi(JComboBox<String> comboBox) {
		for (LichBay lichBay : listLichBay) {
			comboBox.addItem(lichBay.getNoiDi());
		}
	}

	public void duaDuLieuVaoNoiDen(JComboBox<String> comboBox) {
		for (LichBay lichBay : listLichBay) {
			comboBox.addItem(lichBay.getNoiDen());
		}
	}

	// Đưa dữ liệu vào module của table
	public void duaDuLieuVaoModule() {
		for (VeMayBay veMayBay : listVeBay) {
			Duration khoangCach = Duration.between(veMayBay.getMaLichBay().getThoiGianDi(),
					veMayBay.getMaLichBay().getThoiGianDen());
			modeltable.addRow(new Object[] { veMayBay.getMaVe(), veMayBay.getMaHangBay().getTenHangBay(),
					veMayBay.getMaLichBay().getNoiDi(), veMayBay.getMaLichBay().getNoiDen(),
					veMayBay.getMaLichBay().getThoiGianDi(), veMayBay.getMaLichBay().getThoiGianDen(),
					khoangCach.toHoursPart() + "h" + khoangCach.toMinutesPart() + "m", veMayBay.getGia() });

		}
	}
	
//	private ImageIcon loadImageFromPath(String imagePath) {
//	    try {
//	        String basePath = System.getProperty("user.dir"); // Lấy thư mục hiện tại
//	        String fullPath = basePath + imagePath; // Tạo đường dẫn đầy đủ
//	        return new ImageIcon(fullPath); // Nạp và trả về ImageIcon
//	    } catch (Exception e) {
//	        System.err.println("Không thể tải hình ảnh từ đường dẫn: " + imagePath);
//	        return null; // Trả về null nếu nạp thất bại
//	    }
//	}
//	
//	public void duaDuLieuVaoModule() {
//		for (VeMayBay veMayBay : listVeBay) {
//			
//			ImageIcon logoHangBay = loadImageFromPath(veMayBay.getMaHangBay().getHinhAnh());
//			if (logoHangBay == null) {
//			    // Sử dụng một hình ảnh mặc định nếu không tìm thấy
//			    logoHangBay = new ImageIcon("path/to/default/logo.png");
//			}
//	        
//			Duration khoangCach = Duration.between(veMayBay.getMaLichBay().getThoiGianDi(),
//					veMayBay.getMaLichBay().getThoiGianDen());
//			modeltable.addRow(new Object[] { veMayBay.getMaVe(), logoHangBay,
//					veMayBay.getMaLichBay().getNoiDi(), veMayBay.getMaLichBay().getNoiDen(),
//					veMayBay.getMaLichBay().getThoiGianDi(), veMayBay.getMaLichBay().getThoiGianDen(),
//					khoangCach.toHoursPart() + "h" + khoangCach.toMinutesPart() + "m", veMayBay.getGia() });
//
//		}
//		
//	}

	// Ham kiem tra du lieu
	public boolean kiemTraGiuaHaiNgayGiongNhau(LocalDateTime ThoiGianA, LocalDateTime ThoiGianB) {
		return ThoiGianA.toLocalDate().equals(ThoiGianB.toLocalDate());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnDatVe;
    private javax.swing.ButtonGroup btnGrLoaiVe;
    private javax.swing.JButton btnSapXepTheoGia;
    private javax.swing.JButton btnTimVe;
    private javax.swing.JComboBox<String> cbNoiDen;
    private javax.swing.JComboBox<String> cbNoiDi;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdateNgayDi;
    private com.toedter.calendar.JDateChooser jdateNgayVe;
    private javax.swing.JLabel jlbNoiDen;
    private javax.swing.JLabel jlbNoiDi;
    private javax.swing.JLabel jlbThoiGianDi;
    private javax.swing.JLabel jlbThoiGianVe;
    private javax.swing.JRadioButton rdbtnKhuHoi;
    private javax.swing.JRadioButton rdbtnMotChieu;
    // End of variables declaration//GEN-END:variables
}
